---
apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://rawgit.com/ston3o/ethibox/master/charts/charts/searx/icon.png
name: searx
version: 0.1.0
appVersion: 0.13.1
keywords:
  - Search
