---
replicaCount: 1
image:
  repository: ston3o/searx
  tag: latest
service:
  name: searx
  type: NodePort
  externalPort: 8888
  internalPort: 8888
ingress:
  enabled: false
  hosts:
    - searx.local
