---
apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://rawgit.com/ston3o/ethibox/master/charts/charts/wordpress/icon.png
name: wordpress
version: 0.1.0
appVersion: 4.9.1
keywords:
  - Blog
