apiVersion: v1
kind: Service
metadata:
  name: {{ template "ghost.fullname" . }}
  labels:
    app: {{ template "ghost.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    email: {{ .Values.email }}
    category: {{ index .Chart.Keywords 0 }}
    domain: {{ index .Values.ingress.hosts 0 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "ghost.name" . }}
    release: {{ .Release.Name }}
