---
apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://rawgit.com/ston3o/ethibox/master/charts/charts/wekan/icon.png
name: wekan
version: 0.1.0
appVersion: v0.63
keywords:
  - Project-Management
