name: Build and deploy

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12.20'

      - name: Install & Tests
        env:
          SECRET: mys3cr3t
          STRIPE_ENABLED: true
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          CYPRESS_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          CYPRESS_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: |
          yarn
          npm run test:ci

  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: docker build -t ethibox/ethibox:${VERSION} .

      - name: Push the Docker image
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker tag ethibox/ethibox:${VERSION} ethibox/ethibox:latest
          docker push ethibox/ethibox:${VERSION}
          docker push ethibox/ethibox:latest

  cd-prod:
    needs: ci
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.ethibox.fr
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker build \
          --build-arg PREFIX_PATHS=true \
          --build-arg MATOMO_ENABLED=${{ secrets.MATOMO_ENABLED }} \
          --build-arg MATOMO_URL=${{ secrets.MATOMO_URL }} \
          --build-arg MATOMO_SITEID=${{ secrets.MATOMO_SITEID }} \
          --build-arg POSTHOG_ENABLED=${{ secrets.POSTHOG_ENABLED }} \
          --build-arg POSTHOG_URL=${{ secrets.POSTHOG_URL }} \
          --build-arg POSTHOG_APIKEY=${{ secrets.POSTHOG_APIKEY }} \
          -t registry.ethibox.fr/ethibox:${VERSION} .

      - name: Push the Docker image
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          REGISTRY: registry.ethibox.fr
        run: |
          docker tag ${REGISTRY}/ethibox:${VERSION} ${REGISTRY}/ethibox:latest
          docker push ${REGISTRY}/ethibox:${VERSION}
          docker push ${REGISTRY}/ethibox:latest
