---
replicaCount: 1
image:
  repository: ston3o/ethibox
  tag: 0.7.4
service:
  type: NodePort
  port: 4444
ingress:
  enabled: false
traefik:
  imageTag: 1.5.4
  serviceType: NodePort
  ssl:
    enabled: false
    enforced: false
  acme:
    enabled: false
    email: contact@example.com
    challengeType: http-01
    staging: true
    logging: true
    persistence:
      enabled: true
  rbac:
    enabled: false
persistence:
  enabled: true
